/*
 * Copyright (c) 2013 Howard Hughes Medical Institute.
 * All rights reserved.
 * Use is subject to Janelia Farm Research Campus Software Copyright 1.1
 * license terms (http://license.janelia.org/license/jfrc_copyright_1_1.html).
 */

package org.janelia.it.ims.tmog.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 * Creates a dialog panel that overlays the application window components (drawing in the {@link
 * JLayeredPane#MODAL_LAYER} of the layered pane). Because it is still part of the application window, the panel will be
 * hidden when the application window is minimized/iconified.
 *
 * @author Eric Trautman
 */
public class TaskSummaryPanel {
    private JPanel contentPanel;
    private JScrollPane messageScrollPane;
    private JTextArea messageTextArea;
    private JButton okButton;
    private JLabel titleLabel;

    private JLayeredPane layeredPane;
    private ComponentListener layeredPaneResizeListener;

    /**
     * Creates a panel that is not visible.
     *
     * @param title   dialog title.
     * @param message dialog message.
     * @param parent  dialog parent component (used to identify layered panel for application).
     */
    public TaskSummaryPanel(String title,
                            String message,
                            Component parent) {

        titleLabel.setText(title);
        messageScrollPane.setWheelScrollingEnabled(true);

        messageTextArea.setText(message);

        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        layeredPane = JLayeredPane.getLayeredPaneAbove(parent);
        layeredPaneResizeListener = new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                contentPanel.setSize(layeredPane.getSize());
            }
        };

        contentPanel.setVisible(false);
    }

    /**
     * Displays this panel.
     */
    public void display() {
        contentPanel.setSize(layeredPane.getSize());
        layeredPane.add(contentPanel, JLayeredPane.MODAL_LAYER);
        layeredPane.addComponentListener(layeredPaneResizeListener);
        contentPanel.setVisible(true);
    }

    /**
     * Hides this panel and cleans up affected resources.
     */
    public void dispose() {
        contentPanel.setVisible(false);
        layeredPane.remove(contentPanel);
        layeredPane.removeComponentListener(layeredPaneResizeListener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
     * code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        contentPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPanel.add(panel1, BorderLayout.SOUTH);
        okButton = new JButton();
        okButton.setText("OK");
        panel1.add(okButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 10), new Dimension(-1, 10), new Dimension(-1, 10), 0, false));
        messageScrollPane = new JScrollPane();
        contentPanel.add(messageScrollPane, BorderLayout.CENTER);
        messageTextArea = new JTextArea();
        messageTextArea.setEditable(false);
        messageTextArea.setMargin(new Insets(10, 10, 10, 10));
        messageScrollPane.setViewportView(messageTextArea);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        contentPanel.add(panel2, BorderLayout.NORTH);
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null));
        titleLabel = new JLabel();
        titleLabel.setHorizontalAlignment(0);
        titleLabel.setText("Task Summary");
        panel2.add(titleLabel, BorderLayout.CENTER);
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
